install.packages("rjava")
install.packages("tm")
install.packages("SnowballC")
install.packages("wordcloud")
install.packages("RWeka")
install.packages("textir")
install.packages("igraph")
install.packages("qdap")
install.packages("maptpx")

library(rjava)
library(tm)
library(SnowballC)
library(wordcloud)
library(RWeka)
library(textir)
library(igraph)
library(qdap)
library(maptpx)

